In [1]:
import numpy as np

In [2]:
!pip install numpy

In [5]:
arr1 = np.array([1,2,3])

In [6]:
arr1

array([1, 2, 3])

In [7]:
arr2 = np.array([[1,2,3],[3,5,6]])

In [8]:
arr2

array([[1, 2, 3],
       [3, 5, 6]])

In [10]:
np.zeros((3,4)) #toh hame mil gaya 3 by 4 ka zero array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.full((4,6),5)

array([[5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5]])

In [13]:
np.eye(4)  #identy matrix 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
np.arange(0,50,5) #50-1 = 49 

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [20]:
np.linspace(0,100,5)


array([  0.,  25.,  50.,  75., 100.])

In [24]:
np.linspace(0,10,8)

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        ])

In [25]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [26]:
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [30]:
myarr.shape # x:y

(4, 3)

In [29]:
myarr.size #total no. of element  

12

In [31]:
myarr.ndim

2

In [32]:
myarr.dtype

dtype('int64')

In [34]:
myarr1 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]],dtype= 'float32')

In [35]:
myarr1

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]], dtype=float32)

In [38]:
n = myarr.astype('float64')

In [39]:
myarr.dtype

dtype('float32')

In [40]:
myarr2 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])


In [41]:
myarr2.shape

(4, 3)

In [42]:
reshaped = myarr2.reshape((3,4))

In [43]:
reshaped

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [44]:
myarr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [46]:
reshaped1 = myarr2.reshape((2,6))  #2 x 6 = 12 

In [47]:
reshaped1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])