In [1]:
import numpy as np

arr= np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [2]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [3]:
flat = arr.flatten()


In [4]:

flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [5]:
flat[0]

np.int64(1)

In [6]:
flat[3:6]

array([4, 5, 6])

In [7]:
flat[3:]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [8]:
flat[:5]

array([1, 2, 3, 4, 5])

In [9]:
flat


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [19]:
b = flat[3:7].copy()  #copy bana lii  

In [20]:
b

array([4, 5, 6, 7])

In [21]:
b[0] =4444444444

In [22]:
b

array([4444444444,          5,          6,          7])

In [23]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [34]:
arr = np.array(([ 51,  42,  73,  64,  55,  46,  37,  28,  39, 10, 11, 12]))


In [35]:
arr[[1,4,6]]

array([42, 55, 37])

In [36]:
arr[arr>50]

array([51, 73, 64, 55])

In [37]:
import numpy as np

# 1) Create a 3×3 array filled with random numbers and print its shape.
arr1 = np.random.rand(3, 3)
print("1) 3x3 Random Array:\n", arr1)
print("Shape:", arr1.shape)

# 2) Convert an array of floats [1.1, 2.2, 3.3] into integers.
float_arr = np.array([1.1, 2.2, 3.3])
int_arr = float_arr.astype(int)
print("\n2) Integer Array:", int_arr)

# 3) Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6].
original = np.array([1, 2, 3, 4, 5, 6])
even_indices = np.where(original % 2 == 0)
even_numbers = original[even_indices]
print("\n3) Even Numbers (Fancy Indexing):", even_numbers)

# 4) Reshape a 1D array of size 9 into a 3×3 matrix.
arr2 = np.arange(9)  # or use any array of size 9
reshaped = arr2.reshape((3, 3))
print("\n4) Reshaped 3x3 Matrix:\n", reshaped)

# 5) Use boolean masking to filter numbers greater than 50 in an array.
arr3 = np.array([10, 55, 32, 75, 48, 90])
filtered = arr3[arr3 > 50]
print("\n5) Numbers > 50 (Boolean Masking):", filtered)


1) 3x3 Random Array:
 [[0.38097451 0.95193777 0.11854748]
 [0.68914981 0.38600777 0.56797915]
 [0.69423319 0.47143347 0.57450528]]
Shape: (3, 3)

2) Integer Array: [1 2 3]

3) Even Numbers (Fancy Indexing): [2 4 6]

4) Reshaped 3x3 Matrix:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

5) Numbers > 50 (Boolean Masking): [55 75 90]
