In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5,6,7,8,9,0])

In [4]:
np.mean(arr) # Compute the mean (average) of an array.

np.float64(4.5)

In [5]:
np.std(arr)

np.float64(2.8722813232690143)

In [6]:
np.var(arr)

np.float64(8.25)

In [7]:
np.min(arr)

np.int64(0)

In [8]:
np.max(arr)

np.int64(9)

In [9]:
np.sum(arr)

np.int64(45)

In [10]:
np.prod(arr)

np.int64(0)

In [11]:
np.median(arr)

np.float64(4.5)

In [12]:
np.percentile(arr, 3)  # For the 50th percentile (median)

np.float64(0.27)

In [13]:
np.argmax(arr)

np.int64(8)

In [14]:
arr1 = np.array([1,2,3,4]) 
arr2 = np.array([7,8,9,0])
np.corrcoef(arr1, arr2)

array([[ 1.        , -0.63245553],
       [-0.63245553,  1.        ]])

In [15]:
np.unique(arr)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.diff(arr)

array([ 1,  1,  1,  1,  1,  1,  1,  1, -9])

In [17]:
np.cumsum(arr)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 45])

In [18]:
np.linspace(0, 10, 5)  # 5 numbers from 0 to 10

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [19]:
np.log(arr)

C:\Users\navgh\AppData\Local\Temp\ipykernel_8964\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458,       -inf])

In [20]:
np.exp(arr)


array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 1.00000000e+00])