In [2]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])



In [3]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
arr[0]

array([1, 2, 3])

In [5]:
np.sum(arr, axis = 0) #column sum becoz of axis 0

array([12, 15, 18])

In [6]:
np.sum(arr, axis = 1) # row sum becoz of axis 1

array([ 6, 15, 24])

In [7]:
arr[0][1]  # 0 TH row 1 column

np.int64(2)

In [12]:
g =arr[0:2,1:3]

In [13]:
g

array([[2, 3],
       [5, 6]])

In [20]:
arr3D = np.array([[[1, 2, 3],
                   [4, 5, 6]],
                  [[7, 8, 9],
                   [10, 11, 12]]])

# Output of arr3D.shape is → (depth, rows, columns)
print(arr3D.shape) 

(2, 2, 3)


In [21]:
print(arr3D[0,1,2])

6


In [22]:
print(arr3D[:,0,:])

[[1 2 3]
 [7 8 9]]


In [23]:
# Get all rows of the first column
first_col = arr[:, 0]
print(first_col)  # Output: [1 4 7]

[1 4 7]


In [24]:
print(arr3D[0,0,:])

[1 2 3]


In [26]:
arr3D[:,0,:] = 0


In [27]:
arr3D

array([[[ 0,  0,  0],
        [ 4,  5,  6]],

       [[ 0,  0,  0],
        [10, 11, 12]]])