In [19]:
import numpy as np



In [20]:
arr = np.array([1,32,45,56,45,77,5])

In [21]:
arr.dtype

dtype('int64')

In [22]:
arr.astype("float64")   

array([ 1., 32., 45., 56., 45., 77.,  5.])

In [23]:
arr2 = np.array([10, 20, 30], dtype=np.int64)
arr_small = arr2.astype(np.int32)
print(arr_small)  
print(arr_small.dtype)   

[10 20 30]
int32


In [24]:
arr3 = np.array([10, 20, 30], dtype="float32")

In [25]:
arr3

array([10., 20., 30.], dtype=float32)

In [26]:
arr3.nbytes

12

In [27]:
arr2.nbytes

24

In [28]:
arr4 = np.array(['apple', 'banana', 'cherry'], dtype='U10')  # Unicode string array
print(arr4)


['apple' 'banana' 'cherry']


In [31]:
arr5 = np.array([1 + 2j, 3 + 4j, 5 + 6j], dtype='complex128')
print(arr5)

[1.+2.j 3.+4.j 5.+6.j]


In [32]:
arr6 = np.array([{'a': 1}, [1, 2, 3], 'hello'], dtype=object)
print(arr6)

[{'a': 1} list([1, 2, 3]) 'hello']
